name = "day21"
description = "2024 advent of code day 21"
version = "0.1.0-dev"

authors = ["John Perry"]
maintainers = ["John Perry <devotus@yahoo.com>"]
maintainers-logins = ["johnperry-math"]
licenses = "CC-BY-SA-4.0"
website = ""
tags = []
